name: audioplayers_asset_repro
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers:
      git:
          url: git://github.com/luanpotter/audioplayers.git
          ref: master
          path: packages/audioplayers

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  assets:
    - assets/bell.mp3